/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "nano.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MyDouble, MyDouble, 2)


PB_BIND(MyFloat, MyFloat, 2)


PB_BIND(MyInt32, MyInt32, 2)


PB_BIND(MyInt64, MyInt64, 2)


PB_BIND(MyUint32, MyUint32, 2)


PB_BIND(MyUint64, MyUint64, 2)


PB_BIND(MySint32, MySint32, 2)


PB_BIND(MySint64, MySint64, 2)


PB_BIND(MyFixed32, MyFixed32, 2)


PB_BIND(MyFixed64, MyFixed64, 2)


PB_BIND(MySfixed32, MySfixed32, 2)


PB_BIND(MySfixed64, MySfixed64, 2)


PB_BIND(MyBool, MyBool, 2)


PB_BIND(MyParam, MyParam, 2)


PB_BIND(MyFunc, MyFunc, 4)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

